#DEV environment

app:
  message: Este é o arquivo de propriedades para ${spring.application.name} para ambiente de desenvolvimento

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
